book:
  name: '&7Enchanted book: &3%enchant_display_name% %enchant_level%'
  lore:
  - '%enchant_description%'
  - ''
  - '&7Success: &2%success_rate%&7%'
  - '&7Destroy: &4%destroy_rate%&7%'
worlds:
  list:
  - world
  - world_nether
  - world_the_end