main: me.wertik.enchants.Main
author: Wertik1206
version: dev-1.0.3.1
name: Enchants
commands:
  enchants:
    description: Main command to manipulate the plugin.
  ebook:
    description: Book manager command.